import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar/NavBar";
import { AuthProvider } from "@/contexts/AuthContext";

// ——— Fonts: SOLO Roboto y Roboto Condensed ———
import { Roboto } from "next/font/google";
import { Roboto_Condensed } from "next/font/google";
import { CartProvider } from "@/contexts/CardContex";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto-condensed",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${roboto.variable} ${robotoCondensed.variable} antialiased`}
      >
      <AuthProvider>
        <CartProvider>
          <>
            <NavBar />
            <section className="w-full h-30"></section>
            {children}
            <Footer />
          </>
        </CartProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
